site_name: KDM Lernfeld 12

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_KDM_LF12

site_url: https://herr-nm.github.io/MMBbS_KDM_LF12/

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Kapitel 00 - Organisatorisches: 'kapitel_00.md'
    - Kapitel 01 - Geschäftsmodelle und Vertriebswege analysieren: 'kapitel_01.md'
    - Kapitel 02 - Marktanalysen durchführen: 'kapitel_02.md'
    - Kapitel 03 - Unternehmen und ihre Geschäftsmodelle quantitativ auswerten: 'kapitel_03.md'
    - Kapitel 04 - Geschäftsprozesse und -modelle weiterentwickeln: 'kapitel_04.md'
    - Kapitel 05 - Digitale Produkte managen: 'kapitel_05.md'
    - Lösungen: 'loesungen.md'
    

