site_name: KDM Lernfeld 12

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown 

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/KDM-LF12.git

site_url: https://herr-nm.github.io/KDM-LF12/

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Kapitel 00 - Organisatorisches: 'kapitel_00.md'
    - Kapitel 01 - Gesch채ftsmodelle und Vertriebswege analysieren: 'kapitel_01.md'
    - Kapitel 02 - Marktanalysen durchf체hren: 'kapitel_02.md'
    - Kapitel 03 - Unternehmen und ihre Gesch채ftsmodelle quantitativ auswerten: 'kapitel_03.md'
    - Kapitel 04 - Gesch채ftsprozesse und -modelle weiterentwickeln: 'kapitel_04.md'
    - Kapitel 05 - Digitale Produkte managen: 'kapitel_05.md'
    

